language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging

#Build Image: -Feed Service
  - cd ./feedservice-api/www
  - docker build -t feedapi:latest .
  - docker tag feedapi:latest raduartt/feedapi:latest

#Build Image: User Service
  - cd ..
  - cd ../userservice-api/www
  - docker build -t userapi:latest .
  - docker tag userap:latest raduartt/userapi:latest

#Build Image: Reverse-Proxy Service
  - cd ..
  - cd ../reverse-proxy/www
  - docker build -t reverse-proxy:latest .
  - docker tag reverse-proxy:latest raduartt/reverse-proxy:latest

#Build Image: Frontend
  - cd ..
  - cd ../frontend
  - docker build -t frontend:latest .
  - docker tag frontend:latest raduartt/frontend:latest


after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push raduartt/reverse-proxy:latest
  - docker push raduartt/frontend:latest
  - docker push raduartt/userapi:latest
  - docker push raduartt/feedapi:latest
