apiVersion: v1
kind: Service
metadata:
  labels:
    service: userapi-service
  name: userapi-service
  namespace: default
  selfLink: /api/v1/namespaces/default/services/userapi-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    service: userapi-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}



  