apiVersion: v1
kind: Service
metadata:
  labels:
    service: frontend-app
  name: frontend-app
  namespace: default
  selfLink: /api/v1/namespaces/default/services/frontend-app
spec:
  ports:
  - port: 8100
    targetPort: 80
  selector:
    service: frontend-app
  sessionAffinity: None
  type: LoadBalancer



  